cpu-bind=MASK - dlcgpu20, task  0  0 [1879]: mask 0xf0000000f0000 set
INFO:syne_tune.optimizer.schedulers.scheduler_searcher:Master random_seed = 9002
INFO:syne_tune.optimizer.schedulers.scheduler_searcher:max_resource_level = 1, as inferred from config_space
INFO:syne_tune.tuner:results of trials will be saved on /home/sukthank/syne-tune/mogpt-2024-05-30-12-03-50-752
INFO:syne_tune.backend.local_backend:Detected 1 GPUs
DEBUG:syne_tune.backend.local_backend:scheduling 0, /work/dlclarge2/sukthank-hw-llm-bench/arxiv/HW-Aware-LLM-Bench/baselines/gpt_objective_2d.py, {'type': 'quantile', 'search_space': 'm', 'surrogate_type': 'conformal_quantile', 'objective': 'energies', 'device': 'a100', 'num_layers': 23, 'embed_dim': 256, 'bias': True, 'mlp_ratio_0': 4, 'num_heads_0': 16, 'mlp_ratio_1': 2, 'num_heads_1': 16, 'mlp_ratio_2': 3, 'num_heads_2': 12, 'mlp_ratio_3': 3, 'num_heads_3': 16, 'mlp_ratio_4': 2, 'num_heads_4': 12, 'mlp_ratio_5': 2, 'num_heads_5': 16, 'mlp_ratio_6': 2, 'num_heads_6': 12, 'mlp_ratio_7': 3, 'num_heads_7': 8, 'mlp_ratio_8': 3, 'num_heads_8': 12, 'mlp_ratio_9': 4, 'num_heads_9': 16, 'mlp_ratio_10': 3, 'num_heads_10': 16, 'mlp_ratio_11': 4, 'num_heads_11': 16, 'mlp_ratio_12': 2, 'num_heads_12': 8, 'mlp_ratio_13': 3, 'num_heads_13': 12, 'mlp_ratio_14': 4, 'num_heads_14': 8, 'mlp_ratio_15': 2, 'num_heads_15': 8, 'mlp_ratio_16': 2, 'num_heads_16': 16, 'mlp_ratio_17': 4, 'num_heads_17': 12, 'mlp_ratio_18': 4, 'num_heads_18': 12, 'mlp_ratio_19': 2, 'num_heads_19': 12, 'mlp_ratio_20': 2, 'num_heads_20': 12, 'mlp_ratio_21': 3, 'num_heads_21': 8, 'mlp_ratio_22': 2, 'num_heads_22': 16, 'mlp_ratio_23': 4, 'num_heads_23': 8, 'epochs': 1, 'dataset_path': './'}, logging into /home/sukthank/syne-tune/mogpt-2024-05-30-12-03-50-752/0
INFO:syne_tune.backend.local_backend:running subprocess with command: /home/sukthank/anaconda3/envs/hwllm/bin/python /work/dlclarge2/sukthank-hw-llm-bench/arxiv/HW-Aware-LLM-Bench/baselines/gpt_objective_2d.py --type quantile --search_space m --surrogate_type conformal_quantile --objective energies --device a100 --num_layers 23 --embed_dim 256 --bias True --mlp_ratio_0 4 --num_heads_0 16 --mlp_ratio_1 2 --num_heads_1 16 --mlp_ratio_2 3 --num_heads_2 12 --mlp_ratio_3 3 --num_heads_3 16 --mlp_ratio_4 2 --num_heads_4 12 --mlp_ratio_5 2 --num_heads_5 16 --mlp_ratio_6 2 --num_heads_6 12 --mlp_ratio_7 3 --num_heads_7 8 --mlp_ratio_8 3 --num_heads_8 12 --mlp_ratio_9 4 --num_heads_9 16 --mlp_ratio_10 3 --num_heads_10 16 --mlp_ratio_11 4 --num_heads_11 16 --mlp_ratio_12 2 --num_heads_12 8 --mlp_ratio_13 3 --num_heads_13 12 --mlp_ratio_14 4 --num_heads_14 8 --mlp_ratio_15 2 --num_heads_15 8 --mlp_ratio_16 2 --num_heads_16 16 --mlp_ratio_17 4 --num_heads_17 12 --mlp_ratio_18 4 --num_heads_18 12 --mlp_ratio_19 2 --num_heads_19 12 --mlp_ratio_20 2 --num_heads_20 12 --mlp_ratio_21 3 --num_heads_21 8 --mlp_ratio_22 2 --num_heads_22 16 --mlp_ratio_23 4 --num_heads_23 8 --epochs 1 --dataset_path ./ --st_checkpoint_dir /home/sukthank/syne-tune/mogpt-2024-05-30-12-03-50-752/0/checkpoints
INFO:syne_tune.tuner:(trial 0) - scheduled config {'type': 'quantile', 'search_space': 'm', 'surrogate_type': 'conformal_quantile', 'objective': 'energies', 'device': 'a100', 'num_layers': 23, 'embed_dim': 256, 'bias': True, 'mlp_ratio_0': 4, 'num_heads_0': 16, 'mlp_ratio_1': 2, 'num_heads_1': 16, 'mlp_ratio_2': 3, 'num_heads_2': 12, 'mlp_ratio_3': 3, 'num_heads_3': 16, 'mlp_ratio_4': 2, 'num_heads_4': 12, 'mlp_ratio_5': 2, 'num_heads_5': 16, 'mlp_ratio_6': 2, 'num_heads_6': 12, 'mlp_ratio_7': 3, 'num_heads_7': 8, 'mlp_ratio_8': 3, 'num_heads_8': 12, 'mlp_ratio_9': 4, 'num_heads_9': 16, 'mlp_ratio_10': 3, 'num_heads_10': 16, 'mlp_ratio_11': 4, 'num_heads_11': 16, 'mlp_ratio_12': 2, 'num_heads_12': 8, 'mlp_ratio_13': 3, 'num_heads_13': 12, 'mlp_ratio_14': 4, 'num_heads_14': 8, 'mlp_ratio_15': 2, 'num_heads_15': 8, 'mlp_ratio_16': 2, 'num_heads_16': 16, 'mlp_ratio_17': 4, 'num_heads_17': 12, 'mlp_ratio_18': 4, 'num_heads_18': 12, 'mlp_ratio_19': 2, 'num_heads_19': 12, 'mlp_ratio_20': 2, 'num_heads_20': 12, 'mlp_ratio_21': 3, 'num_heads_21': 8, 'mlp_ratio_22': 2, 'num_heads_22': 16, 'mlp_ratio_23': 4, 'num_heads_23': 8, 'epochs': 1, 'dataset_path': './'}
DEBUG:syne_tune.tuner:1 of 1 workers are busy, wait for 5.0 seconds
DEBUG:syne_tune.tuner:1 of 1 workers are busy, wait for 5.0 seconds
DEBUG:syne_tune.tuner:1 of 1 workers are busy, wait for 5.0 seconds
DEBUG:syne_tune.tuner:1 of 1 workers are busy, wait for 5.0 seconds
DEBUG:syne_tune.tuner:1 of 1 workers are busy, wait for 5.0 seconds
DEBUG:syne_tune.tuner:1 of 1 workers are busy, wait for 5.0 seconds
ERROR:syne_tune.tuner:An error happened during the tuning, cleaning up resources and logging final resources before throwing the exception.
DEBUG:syne_tune.tuner:saving tuner in /home/sukthank/syne-tune/mogpt-2024-05-30-12-03-50-752/tuner.dill
INFO:syne_tune.tuner:Stopping trials that may still be running.
INFO:syne_tune.tuner:Tuning finished, results of trials can be found on /home/sukthank/syne-tune/mogpt-2024-05-30-12-03-50-752
Traceback (most recent call last):
  File "/work/dlclarge2/sukthank-hw-llm-bench/arxiv/HW-Aware-LLM-Bench/baselines/run_nas_gpt_2d.py", line 188, in <module>
    tuner.run()
  File "/home/sukthank/anaconda3/envs/hwllm/lib/python3.11/site-packages/syne_tune/tuner.py", line 342, in run
    raise e
  File "/home/sukthank/anaconda3/envs/hwllm/lib/python3.11/site-packages/syne_tune/tuner.py", line 277, in run
    new_done_trial_statuses, new_results = self._process_new_results(
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sukthank/anaconda3/envs/hwllm/lib/python3.11/site-packages/syne_tune/tuner.py", line 428, in _process_new_results
    trial_status_dict, new_results = self.trial_backend.fetch_status_results(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sukthank/anaconda3/envs/hwllm/lib/python3.11/site-packages/syne_tune/backend/trial_backend.py", line 247, in fetch_status_results
    all_trial_results = self._all_trial_results(trial_ids)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sukthank/anaconda3/envs/hwllm/lib/python3.11/site-packages/syne_tune/backend/local_backend.py", line 269, in _all_trial_results
    training_end_time = self._read_time_stamp(trial_id=trial_id, name="end")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sukthank/anaconda3/envs/hwllm/lib/python3.11/site-packages/syne_tune/backend/local_backend.py", line 329, in _read_time_stamp
    return datetime.fromtimestamp(float(f.readline()))
                                  ^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: ''
